### ISSUE TITLE
Tracking: Improvements compared to `jl-generators.cpp`

### ISSUE THREAD

**Issue by jumerckx** [JuliaLLVM/TableGen.jl#1]
* [ ] single unnamed result kwarg should just be called `result`. If there are multiple results, we should accept a tuple of MLIR types. (https://github.com/JuliaLabs/MLIR.jl/issues/83)
* [ ] generate code for enums (e.g. look at `arith.cmpi` attribute)
* [ ] (maybe) generate julia code for creating dialect-specific attributres?
